TRAIN_TWEETS_FILE_NAME = "../resources/clean_training_set.txt"
TRAIN_FEATURES_FILE_NAME = "../resources/feature_matrix.txt"
TEST_TWEETS_FILE_NAME = "../resources/mini_test_set.txt"
TEST_FEATURES_FILE_NAME = "../resources/test_feature_matrix.txt"
POS_TWEETS_FILE_NAME = "plus_smile.txt"
NEG_TWEETS_FILE_NAME = "minus_smile.txt"
DIR_TWEETS_FILES = "../resources/"